### ISSUE TITLE
transparent background image become black after quantize it (lost transparency)

### ISSUE THREAD

**Issue by waelkonsowa** [mcychan/nQuant.cs#2]
* transparent background image become black after quantize it (lost transparency)

before quantize
![empty](https://user-images.githubusercontent.com/65398361/83696436-c7c2de80-a5fc-11ea-8467-936c33eb7d1d.png)

after quantize
![empty-quant256](https://user-images.githubusercontent.com/65398361/83696466-d9a48180-a5fc-11ea-978e-90d0a45ed32a.png)

I used code

            maxColors = 256;

            PnnQuant.PnnQuantizer quantizer = new PnnQuant.PnnLABQuantizer();
            var pixelFormat = (maxColors > 256) ? PixelFormat.Format16bppArgb1555 : (maxColors > 16) ? PixelFormat.Format8bppIndexed : (maxColors > 2) ? PixelFormat.Format4bppIndexed : PixelFormat.Format1bppIndexed;

            using (var bitmap = new Bitmap(sourcePath))
            {
                try
                {
                   // using (var dest = quantizer.QuantizeImage(bitmap, pixelFormat, maxColors, true))
                    using (var dest = quantizer.QuantizeImage(bitmap, pixelFormat, maxColors, true))
                    {
                        dest.Save(targetPath, ImageFormat.Png);
                        System.Console.WriteLine("Converted image: " + targetPath);
                    }
                }
                catch (Exception q)
                {
                #if (DEBUG)
                    System.Console.WriteLine(q.StackTrace);
                #else
                    System.Console.WriteLine(q.Message);
                    System.Console.WriteLine("Incorrect pixel format: {0} for {1} colors.", pixelFormat.ToString(), maxColors);
#endif
                }
            }

**Comment by mcychan** [comment]
I downloaded your image to test. Transparency can be kept without any problem.

**Comment by mcychan** [comment]
after quantize
![83696436-c7c2de80-a5fc-11ea-8467-936c33eb7d1d-quant256](https://user-images.githubusercontent.com/26831069/87171949-03407f00-c306-11ea-9c0c-393d497d946c.png)

**Comment by waelkonsowa** [comment]
Can it be a problem related to my Mac device ?!
As there is exe file that cant be opened on Mac

**Comment by mcychan** [comment]
Current release version is using .net core 3.1
It can be build target to osx-x64
![osx-x64](https://user-images.githubusercontent.com/26831069/87265178-ad7df980-c4f4-11ea-91bd-bb6f34d14f0f.gif)
`brew install mono-libgdiplus`
The following build is a runtime-dependent executable for osx-x64
[nQuant.cs.osx-64.zip](https://github.com/mcychan/nQuant.cs/files/4930317/nQuant.cs.osx-64.zip)
