### ISSUE TITLE
The speed is too slow compared with the original branch

### ISSUE THREAD

**Issue by net10010** [mcychan/nQuant.cs#4]
The speed is too slow compared with the original branch.The bigger the picture, the more obvious it is.
1:Too many for loops
2:Recommended use:Bitmap.LockBits

**Comment by net10010** [comment]
Very good function and idea！

**Comment by mcychan** [comment]
The color lookup table was removed when dithering to improve quality to avoid extra artifacts.
Use unsafe to increase the speed of BitmapUtilities.GrabPixels(...)
